[phases.setup]
nixPkgs = ["python310", "ffmpeg", "libgl1", "libglib2.0-0", "libsm6", "libxext6", "libxrender1"]

[phases.install]
cmds = ["cd vision_safe_ultima_backend_v2.0 && python -m pip install -r requirements.txt"]

[start]
cmd = "cd vision_safe_ultima_backend_v2.0 && uvicorn main:app --host 0.0.0.0 --port $PORT"
