[phases.setup]
aptPkgs = ["libgl1", "libglib2.0-0", "libsm6", "libxext6", "libxrender1", "ffmpeg"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt", "python -m pip uninstall -y opencv-python"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
